{"a192006c5ea5b046def44a61b817b811":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"3cadf4a7058110d1","status":"failed","statusDetails":"Timed out retrying after 4000ms: Expected to find element: `:nth-child(1) > .product-item-info > .photo > .product-image-container > .product-image-wrapper > .product-image-photo`, but never found it.","time":{"start":1682538177861,"stop":1682538188863,"duration":11002}}]},"3395d38fb13475d9007aac1f985aff99":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"e4e80433291bd559","status":"failed","statusDetails":"Timed out retrying after 4000ms: Expected to find element: `:nth-child(1) > .product-item-info > .photo > .product-image-container > .product-image-wrapper > .product-image-photo`, but never found it.","time":{"start":1682538283657,"stop":1682538294616,"duration":10959}}]},"eba97d2ec4b0932fc53319f4533b5f88":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"c267ceb23b21674e","status":"passed","time":{"start":1682526433472,"stop":1682526451395,"duration":17923}}]},"218bdbd6501738265c5f8d380aeb9a4c":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"830dd58ef45133ec","status":"passed","time":{"start":1682538252976,"stop":1682538264537,"duration":11561}}]},"77db65a91071c3fdc9b9d8ace04b4614":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"45a6be3a94b5e98c","status":"failed","statusDetails":"Timed out retrying after 5000ms: Expected to find content: 'Welcome,' but never did.","time":{"start":1682538208162,"stop":1682538219674,"duration":11512}}]},"c59643030e1e776644fd5d1d6aa79cfc":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"d35a7c67b34c6509","status":"failed","statusDetails":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.get()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n\nhttps://on.cypress.io/cannot-execute-commands-outside-test","time":{"start":1682531417636,"stop":1682531417858,"duration":222}}]},"c9580d207f2ff505259776d0288de128":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"4315be81d318eb1c","status":"failed","statusDetails":"`cy.should()` failed because you invoked a command inside the callback. `cy.should()` retries the inner function, which would result in commands being added to the queue multiple times. Use `cy.then()` instead of `cy.should()`, or move any commands outside the callback function.\n\nThe command invoked was:\n\n  > `cy.checkCartNotEmpty()`","time":{"start":1682538188879,"stop":1682538208136,"duration":19257}}]},"0e320c63610d0bd1ab8ebcca5867df0d":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"ff8c275505acffdc","status":"failed","statusDetails":"Timed out retrying after 4000ms: Expected to find content: 'Shopping Cart' but never did.","time":{"start":1682538294639,"stop":1682538317399,"duration":22760}}]},"9d07ab9fb34c6beeb310a1136b5e8f22":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"99cc19ec06166e7d","status":"failed","statusDetails":"Timed out retrying after 5000ms: Expected to find content: 'Welcome,' but never did.","time":{"start":1682538242258,"stop":1682538252960,"duration":10702}}]},"d3c0ca9868f5ac43f2ddad0ba53f6751":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"2f07d432b8c2e0e","status":"failed","statusDetails":"Timed out retrying after 5000ms: Expected to find content: 'A login and a password are required' but never did.","time":{"start":1682538264558,"stop":1682538274853,"duration":10295}}]},"4b4d343bb1b5f5484280b00ac55aaeb7":{"statistic":{"failed":0,"broken":0,"skipped":0,"passed":1,"unknown":0,"total":1},"items":[{"uid":"e98bd992227065eb","status":"passed","time":{"start":1682538234586,"stop":1682538237164,"duration":2578}}]},"05d4f67f4bf00ee4853fc0cb94f26d28":{"statistic":{"failed":1,"broken":0,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"940025c6dc84f61e","status":"failed","statusDetails":"`cy.type()` can only accept a string or number. You passed in: `undefined`\n\nhttps://on.cypress.io/type","time":{"start":1682538231911,"stop":1682538234571,"duration":2660}}]}}